FORMAT: 1A
HOST: https://sec-os-app4.193b.starter-ca-central-1.openshiftapps.com/

# osapp4

osapp4 is a RESTful API that exposes the sample HR MySQL database.

## Countries Collection [/countries]
### List All Countries [GET]
+ Response 200 (application/json)

        [
        ]



## Departments Collection [/departments]
### List All Departments [GET]
+ Response 200 (application/json)

        [
        ]
        
        
## Employees Collection [/employees]
### List All Employees [GET]
+ Response 200 (application/json)

        [
        ]
        
        
## Jobs Collection [/jobs]
### List All Jobs [GET]
+ Response 200 (application/json)

        [
        ]


## Locations Collection [/locations]
### List All Locations [GET]
+ Response 200 (application/json)

        [
        ]
        

## Regions Collection [/regions]
### List All Regions [GET]
+ Response 200 (application/json)

        [
        ]